set-rvm:
    \curl -sSL https://get.rvm.io | bash -s stable --ruby

    rvm reload

install-ruby:
    rvm install 2.5.5

set-ruby:
    rvm use 2.5.5
		
set-gems:
    gem install selenium-webdriver

    gem install cucumber

    gem install byebug

    gem install rspec-expectations

    gem install httparty

    gem install faker
		
		gem install bundler

    bundle install

		bundle update